
DROP TABLE FREEBOARD;
DROP SEQUENCE FREEBOARDSEQ;

CREATE SEQUENCE FREEBOARDSEQ NOCACHE;

CREATE TABLE FREEBOARD (

	SEQ NUMBER PRIMARY KEY,
	FREE_STATE VARCHAR2(20) NOT NULL,
	FREE_TITLE VARCHAR2(30) NOT NULL,
	FREE_WRITER VARCHAR2(30) NOT NULL,
	FREEBOARD_CONTENT VARCHAR2(4000) NOT NULL,
	FREEBOARD_DATE DATE NOT NULL,
	PRIVATE VARCHAR2(30) NOT NULL


);

INSERT INTO FREEBOARD VALUES(


FREEBOARDSEQ.NEXTVAL,'진행중','테스트중','관리자','테스트중입니다.',SYSDATE,'비공개'
);

SELECT * FROM FREEBOARD;