DROP SEQUENCE M_NOSEQ;
DROP TABLE BE_MEMBER CASCADE CONSTRAINTS;

--ȸ�� ��ȣ ������
CREATE SEQUENCE M_NOSEQ NOCACHE;

--ȸ�� ���̺� 
CREATE TABLE BE_MEMBER(
 BE_NO NUMBER NOT NULL,
 BE_ID VARCHAR2(100) NOT NULL,		
 BE_PW VARCHAR2(100) NOT NULL,
 BE_NN VARCHAR2(100) NOT NULL,
 BE_NAME VARCHAR2(100) NOT NULL,
 BE_ADDR VARCHAR2(100) NOT NULL,
 BE_PHONE VARCHAR2(100) NOT NULL,
 BE_EMAIL VARCHAR2(100) NOT NULL,
 BE_ENABLED VARCHAR2(2) DEFAULT 'Y' NOT NULL,
 BE_ROLE VARCHAR2(50) DEFAULT 'L1'NOT NULL,

 CONSTRAINT BE_MEMBER_PK PRIMARY KEY(BE_NO),
 CONSTRAINT BE_MEMBER_UQ_ID UNIQUE(BE_ID),
 CONSTRAINT BE_MEMBER_UQ_EMAIL UNIQUE(BE_EMAIL),
 CONSTRAINT BE_MEMBER_ENABLE_CHK CHECK(BE_ENABLED IN('Y', 'N')),
 CONSTRAINT BE_MEMBER_ROLE_CHK CHECK(BE_ROLE IN('L1', 'L2', 'L3', 'ADM'))
);

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'thal00','1234','����','�ڼҹ�','����� ���ı�','010-1111-3333','pth00@naver.com','Y','ADM');

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'wngus99','1234','���','������','��⵵ ������','010-8888-6666','wn99@naver.com','Y','ADM');

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'tjwjd00','1234','���κ�','������','��⵵ �����','010-3553-5555','moon00@naver.com','Y','ADM');

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'tmddnjs77','1234','Ű��','ä�¿�','��⵵ �����ֽ�','010-6666-7777','cccww11@naver.com','Y','L3');

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'tjdtn44','1234','������','�μ���','��⵵ ������','010-1111-9999','ssuu1919@naver.com','Y','L1');

INSERT INTO BE_MEMBER VALUES(
M_NOSEQ.NEXTVAL, 'wjddn99','1234','����','������','��⵵ �Ⱦ��','010-1234-7777','jwooo00@naver.com',default,default);



SELECT * FROM BE_MEMBER;
-----------------
DROP SEQUENCE FLIST_SEQ;
DROP TABLE BE_FRIEND CASCADE CONSTRAINTS;

--ģ�� ��ȣ ������
CREATE SEQUENCE FLIST_SEQ NOCACHE;

--ģ�� ���̺�
CREATE TABLE BE_FRIEND(
 FLIST_NO NUMBER NOT NULL,
 M1 VARCHAR2(100) NOT NULL,
 M2 VARCHAR2(100) NOT NULL,

 UNIQUE(M1, M2),
 CHECK(M1!=M2),
 CONSTRAINT BE_FRIEND_PK PRIMARY KEY(FLIST_NO),
 CONSTRAINT BE_FRIEND_FK FOREIGN KEY(M1) REFERENCES BE_MEMBER(BE_ID),
 CONSTRAINT FRIEND_FK FOREIGN KEY(M2) REFERENCES BE_MEMBER(BE_ID)
);

INSERT INTO BE_FRIEND VALUES(
FLIST_SEQ.NEXTVAL, 'tmddnjs77', 'wjddn99');

INSERT INTO BE_FRIEND VALUES(
FLIST_SEQ.NEXTVAL, 'wjddn99', 'tmddnjs77');

INSERT INTO BE_FRIEND VALUES(
FLIST_SEQ.NEXTVAL, 'wjddn99', 'wjddn99');

INSERT INTO BE_FRIEND VALUES(
FLIST_SEQ.NEXTVAL, 'tmddnjs77', 'tjdtn44');

INSERT INTO BE_FRIEND VALUES(
FLIST_SEQ.NEXTVAL, 'tjdtn44', 'tmddnjs77');


SELECT * FROM BE_FRIEND;
---------------------
DROP SEQUENCE MSG_SEQ;
DROP TABLE BE_MSG CASCADE CONSTRAINTS;

--���� ��ȣ ������
CREATE SEQUENCE MSG_SEQ NOCACHE;
 
--���� ���̺�
CREATE TABLE BE_MSG(
 MSG_NO NUMBER NOT NULL,
 FLIST_NO NUMBER NOT NULL,
 MSG_CONTENT VARCHAR2(4000),
 MSG_DATE DATE DEFAULT SYSDATE NOT NULL,

 CONSTRAINT BE_MSG_PK PRIMARY KEY(MSG_NO),
 CONSTRAINT FLIST_NO_FK FOREIGN KEY(FLIST_NO) REFERENCES BE_FRIEND(FLIST_NO)
);

INSERT INTO BE_MSG VALUES(
MSG_SEQ.NEXTVAL, 1, 'ù �����Դϴ�. �����?', DEFAULT);

SELECT * FROM BE_MSG;
-------------------


--���� �˻� ��ȣ ������
CREATE SEQUENCE B_NO NOCACHE;

--���� �˻� ���̺�
CREATE TABLE BOOK(
 TITLE VARCHAR2(200) NOT NULL,
 CONTENTS VARCHAR2(200) NOT NULL,
 URL VARCHAR2(200) NOT NULL,
 ISBN VARCHAR2(200) NOT NULL,
 DATETIMETIME LOCALDATETIME,
 AUTHORS VARCHAR2(200) NOT NULL,
 PUBLISHER VARCHAR2(200) NOT NULL,
 TRANSLATORS VARCHAR2(200) NOT NULL,
 PRICE INT NOT NULL,
 SALE_PRICE INT NOT NULL,
 THUMBNAIL VARCHAR2(200) NOT NULL,
 STATUS VARCHAR2(200) NOT NULL

);

DROP SEQUENCE R_NOSEQ ;
DROP TABLE R_BOOK CASCADE CONSTRAINTS;

CREATE SEQUENCE R_NOSEQ NOCACHE;
CREATE TABLE R_BOOK(
 R_NO NUMBER NOT NULL,
 BE_NO NUMBER NOT NULL,
 B_TITLE VARCHAR2(1000) NOT NULL,
 B_AUTHOR VARCHAR2(1000) NOT NULL,
 B_COVER VARCHAR2(1000) NOT NULL,
 ADDDATE DATE DEFAULT SYSDATE,
 
 CONSTRAINT R_BOOK_PK PRIMARY KEY(R_NO),
 CONSTRAINT R_BOOK_FK FOREIGN KEY(BE_NO) REFERENCES BE_MEMBER(BE_NO)
 );



DROP SEQUENCE W_NOSEQ ;
DROP TABLE W_BOOK CASCADE CONSTRAINTS;

CREATE SEQUENCE W_NOSEQ NOCACHE;
CREATE TABLE W_BOOK(
 W_NO NUMBER NOT NULL,
 BE_NO NUMBER NOT NULL,
 B_TITLE VARCHAR2(1000) NOT NULL,
 B_AUTHOR VARCHAR2(1000) NOT NULL,
 B_COVER VARCHAR2(1000) NOT NULL,
 ADDDATE DATE DEFAULT SYSDATE,

 CONSTRAINT W_BOOK_PK PRIMARY KEY(W_NO),
 CONSTRAINT W_BOOK_FK FOREIGN KEY(BE_NO) REFERENCES BE_MEMBER(BE_NO)
);

SELECT * FROM W_BOOK;
SELECT * FROM R_BOOK;

